server.port=8082
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/azaricomm}
spring.data.mongodb.auto-index-creation=true
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
app.rabbitmq.exchange=${RABBITMQ_EXCHANGE:azaricomm.events}
