server:
  port: 8080

spring:
  application:
    name: azaricomm-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/openmrs}

webhook:
  secret: ${WEBHOOK_SECRET:}

openmrs:
  base-url: ${OPENMRS_BASE_URL:http://localhost:8081}
  username: ${OPENMRS_USERNAME:admin}
  password: ${OPENMRS_PASSWORD:Admin123}

crypto:
  secret-key: ${CRYPTO_SECRET_KEY:DitIsMijnSuperGeheimeSleutel123!}
#  Deze sleutel moet exact 32 tekens zijn
logging:
  level:
    com.azaricomm: DEBUG
